### ISSUE TITLE
ksponspeech 데이터 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by MunJeongHyeon** [openspeech-team/openspeech#100]
# ❓ Questions & Help

터미널에서 dataset.test_manifest_dir 을 작성해야하는데 제가 kspon manifest 파일을 공유 받았을 때 manifest 파일에 train, val, test 파일 오디오경로들이 전부 한 파일안에 있는 것을 확인하였습니다. 그래서 저 인자값에는 어떤 것을 줘야하는지 궁금합니다.
또한 제가 봤을 때는 보이지 않았는데 train val 데이터가 셔플이 이루어지나요? 아니면 순서대로 split이 될까요

또한 이전의 질문에서 먼저 manifest 파일을 포맷을 작성한 뒤에 
KsponSpeech - LightningDataModule. 이를 구현하셔야한다고 하셧는데
이코드 안에 manifest 파일을 generate하는 코드가 들어가있는데 그럼 미리 만들필요가
있는지 여쭤보고 싶습니다...

제가 커맨드를 잘 못넘기고 있는것같습니다..ㅠ

**Comment by hasangchun** [comment]
안녕하세요. @MunJeongHyeon 

dataset.test_manifest_dir 인자 값으로는 `eval_clean.trn`, `eval_other.trn` 가 있는 디렉토리를 지정해주시면 됩니다.  [[link]](https://github.com/openspeech-team/openspeech/blob/main/openspeech/datasets/ksponspeech/preprocess/preprocess.py#L160-L173)

train, valid를 앞에서부터 개수대로 나누고, 각각 데이터 셔플을 진행해줍니다. 링크 참고하시면 좋을 것 같아요!  [[link1]](https://github.com/openspeech-team/openspeech/blob/main/openspeech/datasets/ksponspeech/lit_data_module.py#L134-L174)[[link2]](https://github.com/openspeech-team/openspeech/blob/bc4ee158984725657af53876311d451ae0a3683d/openspeech/data/audio/dataset.py#L140-L142)

> 또한 이전의 질문에서 먼저 manifest 파일을 포맷을 작성한 뒤에
KsponSpeech - LightningDataModule. 이를 구현하셔야한다고 하셧는데
이코드 안에 manifest 파일을 generate하는 코드가 들어가있는데 그럼 미리 만들필요가
있는지 여쭤보고 싶습니다...

파일을 generate하는 코드가 들어가있어서 경로 지정만 잘 해주시면 manifest 파일을 generate 하고 학습이 시작됩니다.

**Comment by MunJeongHyeon** [comment]
궁금한 부분이 manifest 파일을 미리 만들어놓고 generate 하는 코드 부분을 제거해도 괜찮을까요? kspon 데이터를 사용하는 것이 아닌 제가 가진 음성데이터를 사용해보려고 합니다.

**Comment by MunJeongHyeon** [comment]
또한 
dataset.test_manifest_dir 인자 값으로는 eval_clean.trn, eval_other.trn 가 있는 디렉토리를 지정해주시면 됩니다. [link]

이렇게 답장을 해주셨는데, kspon manifest 파일 예시에서는 마지막부분엔 test 데이터의 경로 /t 스크립트 /t 토큰 이렇게 들어가 있는데 test 데이터에 대해서도 들어가야하는지 궁금합니다.

**Comment by hasangchun** [comment]
> 궁금한 부분이 manifest 파일을 미리 만들어놓고 generate 하는 코드 부분을 제거해도 괜찮을까요? kspon 데이터를 사용하는 것이 아닌 제가 가진 음성데이터를 사용해보려고 합니다.

네, 미리 만들어놓으시면 제거해도 됩니다.

> 이렇게 답장을 해주셨는데, kspon manifest 파일 예시에서는 마지막부분엔 test 데이터의 경로 /t 스크립트 /t 토큰 이렇게 들어가 있는데 test 데이터에 대해서도 들어가야하는지 궁금합니다.

제가 올바르게 이해한지는 모르겠지만, generate 하는 코드를 제거 하고 manifest 파일을 미리 만들어놓으시는거라면   test 데이터도 동일하게 `데이터의 경로 /t 스크립트 /t 토큰` 으로 해주시면 됩니다.

**Comment by MunJeongHyeon** [comment]
제가 만약 다른 데이터셋으로 돌릴려면 test set에 대한 trn 파일을 만들어야할까요?
또한 manifest 파일에 train+val+test 데이터셋 세개가 다들어가야하는지 아니면 학습용과 테스트용을 분리해서
train_manifest.txt, test_manifest.txt로 분류를해야하는지 궁금합니다.!

**Comment by sooftware** [comment]
다른 데이터셋으로 돌리기 위해서는 코드를 추가해주셔야 합니다.  
현재 librispeech, ksponspeech, aishell 데이터셋을 지원하고 있습니다만, 다른 데이터셋 사용을 위해서는 lightning data module을 새로 만들어주셔야 합니다. KsponSpeech 같은 경우는 특이하게 train/valid 데이터와 test 데이터가 따로 공개되어 어쩔수 없이 분리하여 옵션을 받습니다만, 다른 데이터셋의 경우 dataset_path만 지정하면 알아서 처리되도록 짜여있습니다.

**Comment by MunJeongHyeon** [comment]
네 감사합니다.!!! 혹시 코드문에서 manifest 파일에는 \n이 존재하지 않는다고 되어있는데 제가 승인요청해서 받은 ksponspeech 데이터의 manifest파일에는 \n이 존재해서 질문남깁니다.
