### ISSUE TITLE
성능 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by arabae** [openspeech-team/openspeech#104]
# ❓ Questions & Help
**Librispeech, conformer** 기준으로 직접 이 repo로 훈련하신 **모델의 WER**이 어느 정도인지 궁금합니다.

**Comment by sooftware** [comment]
직접 트레이닝 하지는 않았지만, 저희 레포 사용자분께서 Conforemr-CTC 모델로 CER 기준 2점대, WER 기준 11점대를 기록했습니다.    
해당 기록은 LM을 결합하지 않은 결과입니다.  
  
저희도 회사 차원이 아니라 개인적으로 진행하는 프로젝트라 GPU의 부재로 인해 직접 학습을 끝까지 해보지는 못했습니다.    
저희도 모델별로 학습을 해보고 정확한 정보를 제공해드리고 싶은데 아쉽네요. 😢

**Comment by arabae** [comment]
아 그렇군요! 답변 감사합니다 :) 한가지 더 궁금한게 있습니다.
제가 WER, CER 계산에 사용 되는 targets[:, 1:]과 prediction을 출력해봤는데 metric 계산이 올바르게 되는건지 궁금합니다.

**Comment by arabae** [comment]
### WER: 33.2
### CER: 46.75182481751825
---
- targets[:, 1:]

    tensor([
    [ 12, 351, 4, 1240, 142, 8, 4, 1374, 5, 2947, 5, 218, 15, 52, 64, 1784, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 13, 17, 11, 10, 2620, 26, 1031, 17, 13, 35, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 56, 111, 147, 34, 457, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 4, 1506, 229, 801, 7, 27, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], device='cuda:1')

- predictions

    tensor([[3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988],
    [3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988],
    [3988, 3859, 3988, 3988, 3988, 3988, 3859, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859],
    [3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859,
    3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859, 3859]],
    device='cuda:1')

**Comment by arabae** [comment]
### WER: 17.7857
### CER: 26.0374
---

- targets[:, 1:]

    tensor([
    [ 55, 31, 76, 33, 88, 8, 16, 1221, 6, 4540, 999, 8, 4, 4067, 8, 4, 3614, 48, 17, 262, 1572, 5, 1314, 26, 10, 3932, 8, 4, 3008, 2],
    [3785, 12, 2430, 4, 755, 0, 143, 8, 41, 1633, 22, 20, 5, 81, 4, 2252, 20, 5, 214, 68, 20, 5, 46, 12, 166, 7, 2, 0, 0, 0],
    [ 59, 12, 133, 72, 13, 701, 7, 41, 905, 6, 113, 7, 1252, 14, 15, 112, 81, 41, 214, 26, 667, 526, 5, 2, 0, 0, 0, 0, 0, 0],
    [ 56, 4348, 283, 476, 22, 750, 238, 1709, 7, 70, 2801, 103, 4, 2099, 52, 132, 10, 2447, 8, 2376, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0]], device='cuda:0')

- predictions

    tensor([[3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988],
    [3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988],
    [3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988],
    [3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988,
    3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988, 3988]],
    device='cuda:0')

**Comment by sooftware** [comment]
@hasangchun @arabae 어떤 모델로 어떤 커맨드로 하셨을 때 이런 결과가 나오는지 알 수 있을까요?

**Comment by arabae** [comment]
Conformer 모델을 사용했습니다.

```
python ./openspeech_cli/hydra_train.py \
    dataset=librispeech \
    dataset.dataset_download=False \
    dataset.dataset_path=$DATASET_PATH \
    dataset.manifest_file_path=$MANIFEST_FILE_PATH \  
    tokenizer=libri_subword \
    model=conformer \
    audio=fbank \
    lr_scheduler=warmup_reduce_lr_on_plateau \
    trainer=gpu \
    criterion=cross_entropy
  ```
  이렇게 사용했던 것 같습니다.

**Comment by sooftware** [comment]
evaluate 했던 커맨드도 같이 올려주시겠어요?  
지금 올려주신게 학습이 진행된 모델이 인퍼런스 했을때 결과일까요?  
아니면 학습 안된 모델인데 메트릭 측정이 이상해서 질문을 주신걸까요?

**Comment by arabae** [comment]
학습 안된 모델인데 메트릭 측정이 이상해서 질문드렸습니다!

**Comment by sooftware** [comment]
감사합니다. 메트릭 관련해서 확인해보겠습니다.  
  
@hasangchun 메트릭 확인 한 번 해볼래요?  
저번에 테스트했던걸로 알고있는데.

**Comment by sooftware** [comment]
@hasangchun 그런데 일치하는게 하나도 없어보이는데 CER과 WER이 100이 안 나오는게 이상해요. 한 번 확인해주세요.

**Comment by sooftware** [comment]
위에 결과 올려주신거를 메트릭 함수에 넣어서 결과 확인하면 될 것 같네요.

**Comment by sooftware** [comment]
@hasangchun 이거 혹시 테스트 해봤나요?

**Comment by hasangchun** [comment]
@sooftware   저는 ksponspeech로 테스트 해봤는데 메트릭 계산 잘 됩니다. 결과값으로 1.0이 나와야 cer 100인데, 위의 결과 값들은 1보다 큰 17, 26 값이 나온 것입니다. 

그 이유는 cer을 계산할 때, 틀린 개수 / target 길이  로 계산되는데  위의 CER: 26.0374 나온 결과 첫번째 텐서를 비교해보면 target길이는 29, 틀린 개수는 249로  249 / 29 = 8.58정도가 나옵니다. 배치 4개가 누적돼서 계산 되니까 올바르게 계산 되었다고 생각합니다!
