### ISSUE TITLE
성능 확인 및 AM, LM 학습방법

### ISSUE THREAD

**Issue by miziworld** [openspeech-team/openspeech#106]
안녕하세요, 오랜만에 다시 돌아와보니 개발진행이 많이 이루어진것 같네요!
시간이 되어 Openspeech를 이용하여 다시 STT진행해보려고 하는데
몇가지 궁금한점이 있어 질문드립니다. 

1. 현재 Openspeech를 이용하여 전에 말씀주셨던 wer 2 대의 inference가 되는지,
아무래도 트레이닝 시간이 오래걸리다보니 검증이 확실히 끝난 모델은 어떤것이 있는지 알고싶습니다.

2. hydra_train.py과 hydra_train_lm.py(?)가 따로 존재하는것같던데
hydra_train.py에서는 AM 학습만 진행이 되는것인가요?
그렇다면 AM+LM과정은 어떻게 진행되는것인지 궁금합니다.

**Comment by sooftware** [comment]
안녕하세요. 현재는 AM, LM 따로따로 트레이닝 하는 기능만 있으며, 결합해서 인퍼런스 하는 코드는 아직 개발되지 않았습니다.  
아무래도 회사일을 하면서 따로 개인적인 프로젝트를 진행하기가 힘든 상황입니다. 인퍼런스의 경우 어떤 모델 사용하실지를 알아야 답변 가능할 것 같습니다.
