### ISSUE TITLE
gpu-resume 관련해서

### ISSUE THREAD

**Issue by MunJeongHyeon** [openspeech-team/openspeech#111]
# ❓ Questions & Help

gpu-resume 관련해서 질문이 있습니다. 지정해준 해당 체크포인트부터 학습이 진행될텐데 이전에 예를 들어 이전 초기 에폭을 10으로 설정했고, 만약 5에폭에서 중단되었다면, epoch 설정을 10으로 해야할까요 남은 에폭을 계산해서 설정해야할까요?

**Comment by MunJeongHyeon** [comment]
안녕하세요 las 모델 돌렸을 때, 122에폭에서 아래와 같은 에러가 발생하여, 다시 학습을 122에폭부터 돌리려고 해도 같은 에러가 계속해서 반복되어서 질문 남깁니다.
![Screenshot from 2021-10-18 21-29-29](https://user-images.githubusercontent.com/77957228/137730567-35ae6893-998c-455d-90fe-871fa38187cf.png)


RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by MunJeongHyeon** [comment]
네 감사합니다. 해결했습니다.

hydra_eval 하는 과정에서 util.py에 있는 get_class_name이 제대로 import가 되지 않는 것 같습니다.!
![Screenshot from 2021-10-21 00-41-38](https://user-images.githubusercontent.com/77957228/138126007-d73f9aea-773d-4e97-a51c-24548c39cc06.png)

**Comment by sooftware** [comment]
cc. @upskyy
