### ISSUE TITLE
kspon_subword_labels.csv file is missing

### ISSUE THREAD

**Issue by jun-danieloh** [openspeech-team/openspeech#121]
# ❓ Questions & Help
I am not able to download kspon_subword_labels.csv file from README. It looks like it is missing. Can you check it?

**Comment by upskyy** [comment]
@jun-danieloh  We are providing the pre-trained sentencepiece vocab and sentencepiece model file instead of the kspon_subword_labels.csv file.

**Comment by jun-danieloh** [comment]
@upskyy Thanks for your answers!
