### ISSUE TITLE
ksponspeech eval data에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by MYMY-young** [openspeech-team/openspeech#124]
# ❓ Questions & Help

## Details
안녕하세요.
코드를 실행하던 도중 ksponspeech 데이터에 대해 의문이 생겨서 질문드립니다.
일반적인 train data는 제대로 수행이 되는데 eval_other 폴더에 있는 test data에 대해서 
np.memmap에서 ValueError: Size of available data is not a multiple of the data-type size. 가 발생합니다.

제가 따로 파이썬 파일에서 np.memmap을 실행해보았을때도
KsponSpeech_000001.pcm 와 같은 파일에 대해서는 에러가 발생하지 않지만
eval_other에 존재하는 KsponSpeech_E00016.pcm과 같은 파일은 np.memmap을 실행했을때 ValueError가 발생하는데, 

혹시 이에 대한 조언을 얻을 수 있을까해서 질문올립니다.

감사합니다!

**Comment by sooftware** [comment]
음 경로가 잘못 설정된게 아닐까 싶네요. 답이 늦어 죄송합니다

**Comment by upskyy** [comment]
related issues #151
