### ISSUE TITLE
Minor issue when scaling ContextNet

### ISSUE THREAD

**Issue by resurgo97** [openspeech-team/openspeech#128]
If you use contextnet and declare the size other than "medium", (ex. "small")
the dimension of the encoder is resized properly, (self.encoder)
but the linear layer is not rescaled which actually should be. (self.fc)

Users can easily find it and manually modify the code, but here is a minor bug in the codes.

**Comment by upskyy** [comment]
Wow! Thanks for letting me know. I'll fix it ! 😄
