### ISSUE TITLE
How to preprocess datasets？

### ISSUE THREAD

**Issue by wblwty** [openspeech-team/openspeech#131]
# ❓ Questions & Help

I'm sorry to bother you, but I'm having some problems.

I wonder how OpenSpeech preprocesses the dataset. I see preprocess, but I don't see start up. I wonder how I should use it to get Manifest.

I sent an email, but I didn't get a reply.

**Comment by upskyy** [comment]
I have responded to all emails, which dataset do you want to use?

**Comment by wblwty** [comment]
I need manifest of KsponSpeech ,If possible, please send to wb724483933@163.com

**Comment by wblwty** [comment]
> I have responded to all emails, which dataset do you want to use?
I can train it myself manifes？I can't find the code for this part，Can you tell me about it? thank you

**Comment by wblwty** [comment]
I wanted to run lit_data_module.py to get the manifest, but

/home/iip/anaconda3/envs/openspeech/bin/python3.7 /home/iip/wb/openspeech/openspeech/datasets/ksponspeech/lit_data_module.py
Traceback (most recent call last):
  File "/home/iip/wangbo/openspeech/openspeech/datasets/ksponspeech/lit_data_module.py", line 41, in <module>
    class LightningKsponSpeechDataModule(pl.LightningDataModule):
  File "/home/iip/wangbo/openspeech/openspeech/datasets/__init__.py", line 46, in register_data_module_cls
    raise ValueError(f"Cannot register duplicate data module ({name})")
ValueError: Cannot register duplicate data module (ksponspeech)



Process finished with exit code 1

**Comment by upskyy** [comment]
When you run hydra_train.py, a manifest file is created in the path you specified. [[LINK]](https://github.com/openspeech-team/openspeech#training-examples)  
And KsponSpeech needs permission from AI Hub. So please send e-mail including the approved screenshot to openspeech.team@gmail.com.  [[LINK]](https://github.com/openspeech-team/openspeech#pre-processed-manifest-files)  
[This](https://github.com/openspeech-team/openspeech/blob/main/openspeech/datasets/ksponspeech/lit_data_module.py#L68-L97) is the code that preprocesses the data to generate a manifest file. 


I recommend that you read the README.md carefully.
Thanks.

**Comment by wblwty** [comment]
> When you run hydra_train.py, a manifest file is created in the path you specified. [[LINK]](https://github.com/openspeech-team/openspeech#training-examples) And KsponSpeech needs permission from AI Hub. So please send e-mail including the approved screenshot to [openspeech.team@gmail.com](mailto:openspeech.team@gmail.com). [[LINK]](https://github.com/openspeech-team/openspeech#pre-processed-manifest-files) [This](https://github.com/openspeech-team/openspeech/blob/main/openspeech/datasets/ksponspeech/lit_data_module.py#L68-L97) is the code that preprocesses the data to generate a manifest file.
> 
> I recommend that you read the README.md carefully. Thanks.
Ok, thank you

**Comment by afterrealism** [comment]
I also got stuck on this poin.t I ended up creating the manifest file :D Maybe removing this option dataset.manifest_file_path in cli script and creating manifest in dataset.dataset_path might be a way to go.
