### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'log_probs'

### ISSUE THREAD

**Issue by yunigma** [openspeech-team/openspeech#135]
# ❓ Questions & Help
Hello and thank you very much for openspeech!
When I run the ContextNet Trainer, I am getting the ```TypeError: forward() got an unexpected keyword argument 'log_probs'```.
I assume it can be a version problem. I tried few different but I am confused what it should be. On the main page, it is written that the  ```torchaudio==0.6.0```, yet it is not specified in the ``ìnstall.sh``.

## Details
Have tried:
```
torch: 1.10.1
torchaudio: 0.10.1
pytorch_lightning: 1.5.8
```
and
```
torch: 1.6.0
torchaudio: 0.6.0
pytorch_lightning: 1.4.0
```
Thank you in advance!

Iuliia

**Comment by upskyy** [comment]
Thank you for reporting the bug. Could you please write the log together?

**Comment by yunigma** [comment]
Hi! Thanks for your reply! When I switched from ```model=contextnet``` to ```model=contextnet_lstm```, the problem has gone. So, I proceeded with contextnet_lstm and now it starts training and I only have the ```RuntimeError: CUDA out of memory.```
If you want I can any way give logs for ```model=contextnet```, if it would be useful for you.

Sincerely,
Iuliia

**Comment by yunigma** [comment]
Now, I am also experiencing the following issue: ```python3.8/multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.```
Do you have any ideas?
Thanks

**Comment by ccyang123** [comment]
@yunigma How did you solve the resource leak problem?  
I also met the same problem during the training, the error message is as below: 

/usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
./asr.sh: line 1: 4148814 Bus error               (core dumped)

**Comment by ZJsheep** [comment]
Same issue with Conformer and cross_entropy loss. Switch to conformer_lstm or using ctc loss will solve the problem for a while, but still this remains to be a problem.
