### ISSUE TITLE
ImportError: cannot import name 'MISSING' from 'omegaconf'

### ISSUE THREAD

**Issue by jingzhang0909** [openspeech-team/openspeech#137]
# ❓ Questions & Help

does someone come across the problem?
 ImportError: cannot import name 'MISSING' from 'omegaconf'

## Details

![无标题](https://user-images.githubusercontent.com/76758812/150499044-62130189-70bf-4f99-bd45-525b4191fd3e.png)

**Comment by upskyy** [comment]
Please write down all commands and logs.
