### ISSUE TITLE
RuntimeError: Internal: /sentencepiece/python/bundled/sentencepiece/src/trainer_interface.cc(396) [!sentences_.empty()]

### ISSUE THREAD

**Issue by jingzhang0909** [openspeech-team/openspeech#138]
# ❓ Questions & Help

I come across a problem as title when generating the manifest files. Does someone know the reason? How to fix it?
I choose to get a new generate_file for time reason and just keep part of Librispeech to train.

**Comment by upskyy** [comment]
Please write down all commands and logs.
