### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../../LibriSpeech/sp.model'

### ISSUE THREAD

**Issue by tand22** [openspeech-team/openspeech#144]
# ❓ Questions & Help

Getting stuck at this point when trying to run training. Does my shell command look correct?

## Details

<img width="1439" alt="Screen Shot 2022-02-28 at 11 02 17 am" src="https://user-images.githubusercontent.com/10137933/155905744-e1678292-f509-406f-8ae9-3f8bbeacfdda.png">

<img width="392" alt="Screen Shot 2022-02-28 at 11 00 10 am" src="https://user-images.githubusercontent.com/10137933/155905653-031d3773-f96a-4922-9ef2-9dc356ac620d.png">

**Comment by sooftware** [comment]
Can you attach the command?

**Comment by tand22** [comment]
`python ./openspeech_cli/hydra_train.py dataset=librispeech dataset.dataset_download=False dataset.dataset_path=/home/tand/Projects/openspeech/libri/LibriSpeech dataset.manifest_file_path=/home/tand/Projects/openspeech/libri/LibriSpeech/libri_subword_manifest.txt tokenizer=libri_subword model=rnn_transducer audio=fbank lr_scheduler=warmup_reduce_lr_on_plateau trainer=gpu criterion=cross_entropy`

**Comment by sooftware** [comment]
Can you show me the 5 examples of `libri_subword_manifest.txt`?

**Comment by sooftware** [comment]
Do it without specifying the dataset.manifest_file_path.

**Comment by tand22** [comment]
Hmm I don't have a `libri_subword_manifest.txt`. Just tried without specifying the dataset.manifest_file_path and unfortunately it's still the same error.

**Comment by tand22** [comment]
<img width="382" alt="Screen Shot 2022-02-28 at 8 55 36 pm" src="https://user-images.githubusercontent.com/10137933/155962717-8f297e33-67fc-4ced-8e85-ebcdeb4af0fd.png">

I found sp.model, located here.

**Comment by tand22** [comment]
Managed to solve the issue by moving the LibriSpeech directory up a level
