### ISSUE TITLE
Coral TPU 를 사용할 수 있을까요?

### ISSUE THREAD

**Issue by tmvkrpxl0** [openspeech-team/openspeech#150]
현재 제가 사용하는 GPU는 GTX 1050 입니다. VRAM 이 2GB 밖에 되지 않아 훈련시키는데 큰 어려움이 있습니다.
그렇기 때문에, 구글의 Coral TPU 를 이용할 계획입니다, Hydra 에서도 TPU 사용을 지원하는 것으로 보이는데 가능할까요?
만약 사용할 수 있다면, 다수의 TPU가 컴퓨터에 장착되어 있으면 훈련이 더 빠르게 될까요?

**Comment by sooftware** [comment]
TPU는 사용이 어렵습니다. 베이스가 토치여서요.
