### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sos_id'

### ISSUE THREAD

**Issue by MunJeongHyeon** [openspeech-team/openspeech#153]
# ❓ Questions & Help

![스크린샷, 2022-04-15 00-38-20](https://user-images.githubusercontent.com/77957228/163424879-d3c6c970-4b2c-4078-804b-d1b2a465064a.png)

transformer 모델을 돌리려고 하는데 이와 같은 에러가 발생합니다.

**Comment by upskyy** [comment]
@MunJeongHyeon 전체 커맨드 다 적어주시겠어요?

**Comment by MunJeongHyeon** [comment]
새로운 데이터로 학습하지만, 한국어 모델에 예전에 openspeech에서 사용했던 kspon_character_labels.csv로 vocab을 설정했습니다.

커맨드창입니다.
python ./openspeech_cli/hydra_train.py \
dataset=ksponspeech \
dataset.dataset_path=/home/nextgen/Desktop/mjh/325_prac/ \
dataset.manifest_file_path=/home/nextgen/Desktop/mjh/325_prac/manifest.txt \
dataset.test_dataset_path=/home/nextgen/Desktop/mjh/325_prac/ \
dataset.test_manifest_dir=/home/nextgen/Desktop/mjh/325_prac/ \
tokenizer=kspon_character \
model=transformer \
audio=melspectrogram \
lr_scheduler=warmup_reduce_lr_on_plateau \
trainer=gpu \
criterion=cross_entropy

이전 컴퓨터에서는 ( 2021년 후반) 다른 모델을 학습해본적이 있습니다!!!

**Comment by MunJeongHyeon** [comment]
![스크린샷, 2022-04-19 16-51-15](https://user-images.githubusercontent.com/77957228/163953191-bc6d85e2-bac5-468f-bcb2-1d05ea782e89.png)

**Comment by upskyy** [comment]
@MunJeongHyeon  아마 label 파일에 sos token이 없어서 그런 것 같은데요.
[kspon_character_label.csv](https://github.com/openspeech-team/openspeech/files/8513095/kspon_character_label.csv)

이걸로 해보시겠어요? 그리고 최신 코드로 업데이트해서 진행하시는 걸 추천드려요. 동일 커맨드로 학습 되는 것 확인했습니다!

**Comment by MunJeongHyeon** [comment]
네 code와 가상환경은 최신버전으로 업데이트했습니다.
vocab 파일을 올려주신 파일로 변경을 했음에도 불구하고 같은 오류가 발생합니다..

**Comment by voiagerd** [comment]
저도 같은 에러가 떴었는데 디버깅 결과 저 같은 경우는 pytorch lightening 내에 setup 이름의 메소드와 openspeech/datsets/ksponspeech/lit_data_module.py 내 setup 메소드가 이름이 중복되어서 발생했습니다

lit_data_modul.py setup 메소드를 다른 이름으로 변경했더니 에러 해결되었습니다!

**Comment by MunJeongHyeon** [comment]
감사합니다!! lit_data_modul.py의 setup 메소드의 이름 변경과 hydra_train.py의 data_module.setup의 이름을 변경하니 해결됐습니다!!!

**Comment by upskyy** [comment]
@voiagerd @MunJeongHyeon
lit_data_module.py 내 setup 메소드가 pytorch lightning 내의 setup 메소드를 오버라이딩 해야되는데, 매개변수를 동일하게 하지않아서 발생한 문제인 것 같아요. 수정해놓겠습니다. 이슈 감사합니다!

[lit_data_module.py setup](https://github.com/openspeech-team/openspeech/blob/main/openspeech/datasets/ksponspeech/lit_data_module.py#L134-L174) 
[pytorch lightning  setup](https://github.com/PyTorchLightning/pytorch-lightning/blob/9b2b1bb494f928137be67e325b3fc8544a3bf321/pytorch_lightning/core/hooks.py#L342-L421)

**Comment by upskyy** [comment]
#164 로 해결했습니다.
이슈 클로즈하겠습니다.
