### ISSUE TITLE
RuntimeError: The size of tensor a (5001) must match the size of tensor b (5000) at non-singleton dimension 1

### ISSUE THREAD

**Issue by K-BS** [openspeech-team/openspeech#154]
# ❓ Questions & Help

Transformer 모델을 돌렸을 때 에러가 발생해서 질문 남깁니다.

RuntimeError: The size of tensor a (5001) must match the size of tensor b (5000) at non-singleton dimension 1

**Comment by K-BS** [comment]
학습이 진행되는 도중에 발생했습니다.

**Comment by upskyy** [comment]
@K-BS 전체 커맨드와 로그 다 적어주시겠어요?

**Comment by K-BS** [comment]
![Screenshot from 2022-05-01 21-27-52](https://user-images.githubusercontent.com/74411831/166145917-1012225f-74bb-41f1-a9a5-72e95f887fd7.png)
에러 창입니다.
![Screenshot from 2022-05-01 21-28-30](https://user-images.githubusercontent.com/74411831/166145939-5552203e-bdfa-4a89-b393-d5bd61a3b8de.png)
학습 진행상황입니다.

python ./openspeech_cli/hydra_train.py \
dataset=ksponspeech \
dataset.dataset_path=/home/nextgen/Desktop/mjh/325_prac/ \
dataset.manifest_file_path=/home/nextgen/Desktop/mjh/325_prac/manifest.txt \
dataset.test_dataset_path=/home/nextgen/Desktop/mjh/325_prac/ \
dataset.test_manifest_dir=/home/nextgen/Desktop/mjh/325_prac/ \
tokenizer=kspon_character \
model=transformer \
audio=melspectrogram \
lr_scheduler=warmup_reduce_lr_on_plateau \
trainer=gpu \
criterion=cross_entropy

transformer 커맨드창입니다.

다른 las 모델 등은 잘 작동되는 것을 확인했습니다.

**Comment by upskyy** [comment]
답변이 늦어 죄송합니다. @K-BS 

제가 동일한 커맨드로 진행했을 때는 학습이 잘 되는 것을 확인했습니다. 
아마도 label, manifest 파일 때문에 발생하는 에러라고 생각됩니다. 
최신 버전으로 다시 install 해서 진행주시면 좋을 것 같습니다. 추가로 제가 사용한 label 파일 첨부드립니다. 

[kspon_character_label.csv](https://github.com/openspeech-team/openspeech/files/8748673/kspon_character_label.csv)

**Comment by upskyy** [comment]
issue close 하겠습니다. issue 있으시면  reopen 해주세요.
