### ISSUE TITLE
csv file in tokenizer will generate?

### ISSUE THREAD

**Issue by hyoje42** [openspeech-team/openspeech#168]
# ❓ Questions & Help
Hi. First of all thanks for sharing this interesting work.
I tried to run your code but I failed because there is no csv file for the tokenizer.

## details
my command is
![image](https://user-images.githubusercontent.com/35217135/171798605-7e4da0f2-1420-4496-869b-0ab9f3c72e4c.png)

I cannot find 'csv file' for the tokenizer in README.

when I read other issues #20, #134  they said the csv label file will generate by automatic.

I also set the directory structure of dataset as you mentioned in README.

please let me know if I'm wrong.

Thanks in advance.

**Comment by upskyy** [comment]
@hyoje42 
When `hydra_train.py` is executed, the csv file is created in the specified path. Would you like to train with this csv file?
[kspon_character_label.csv](https://github.com/openspeech-team/openspeech/files/8840355/kspon_character_label.csv)

**Comment by hyoje42** [comment]
@upskyy 
Thanks for your quick reply and the csv file! 
By the way, where is the creation part of csv file in your code? I cannot find it. In my opinion, the function 'generate_character_labels' in [character.py](https://github.com/openspeech-team/openspeech/blob/main/openspeech/datasets/ksponspeech/preprocess/character.py) should use somewhere.

**Comment by upskyy** [comment]
@hyoje42 
the function is used [here](https://github.com/openspeech-team/openspeech/blob/main/openspeech/datasets/ksponspeech/lit_data_module.py#L68-L132)!

**Comment by hyoje42** [comment]
@upskyy 
Thanks for the kind reply! 

By the way, I found out why the label csv file could not be generated automatically. I set the [dataset.manifest_file_path] argument to a directory (I thought the auto-generated files would be there). The path of directory exists, so it seems that the csv file and manifest file are not created [code](https://github.com/openspeech-team/openspeech/blob/7eb773979dad2687ecc70e04a8286f3b462e7d02/openspeech/datasets/ksponspeech/lit_data_module.py#L127).
