### ISSUE TITLE
 a circular import

### ISSUE THREAD

**Issue by balabala233333** [openspeech-team/openspeech#194]
## Environment info
run in colab and my computer windows and linux

## Information

Model I am using (test_conformer in tests):
ImportError: cannot import name 'OpenspeechDecoder' from partially initialized module 'openspeech.decoders' (most likely due to a circular import) (/content/openspeech/openspeech/decoders/__init__.py)

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

## To reproduce

1.
2.
3.

**Comment by grazder** [comment]
i've got the same problem

**Comment by Joll123** [comment]
@grazder have you solved it?

**Comment by upskyy** [comment]
Solved with #195
