### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Joll123** [openspeech-team/openspeech#196]
# ❓ Questions & Help
when I run hydra_train.py, I met the problem with "ImportError: cannot import name 'OpenspeechDecoder' from 'openspeech.decoders' (/Users/jinhonglong/Desktop/openspeech/openspeech/decoders/__init__.py)".

**Comment by upskyy** [comment]
Can you download the latest version and try again?

**Comment by upskyy** [comment]
Solved with #195
