### ISSUE TITLE
Importing lightning correctly

### ISSUE THREAD

**Issue by pfeatherstone** [openspeech-team/openspeech#200]
## Environment info
- Platform: Ubuntu 22
- Python version: 3.10.6
- PyTorch version (GPU?): 2.0.1

## Information

It would be great if this repo imported the new Pytorch Lightning module as follows:
```import lightning``` instead of  ```import pytorth_lightning```

**Comment by upskyy** [comment]
The code was written in `pytorch-lightning==1.14.0`.

We should version up this code.
