### ISSUE TITLE
Error in generate lable

### ISSUE THREAD

**Issue by hyungraelee** [openspeech-team/openspeech#206]
### Bug

https://github.com/openspeech-team/openspeech/blob/1b8101b667b0a5018dc1542c106115aad8eacb30/openspeech/datasets/ksponspeech/preprocess/grapheme.py#L87C9-L87C19

안녕하세요, 먼저 좋은 프로젝트를 공유해주셔서 감사합니다 :)
`grapheme` tokenizer의 학습 데이터 레이블 생성 중 에러가 있어 공유드립니다.
위 링크의 코드에서 `idx + 4` 로 시작을 해야 올바른 학습 데이터가 생성됩니다.

Hello, first of all, thank you for sharing a good project :)
I'm sharing this because there was an error creating the training data label of `grapheme` tokenizer.
In the code above link, you must start with `idx + 4` to generate the correct training data.

**Comment by upskyy** [comment]
@hyungraelee 
I think the bug is correct. Thank you for reporting.
If you don't mind, you can write it as a PR.
