### ISSUE TITLE
XXX.pcm is not Valid!!

### ISSUE THREAD

**Issue by oh-young-data** [openspeech-team/openspeech#222]
hello!!

I am learning with Ksponspeech.

In the evaluation (eval data) part after trainning, 

ValueError        xxxxxxxxxxxxx.pcm is not Valid!! An error occurs.

Has anyone experienced the same error?

The same error seems to occur even if you change the pcm file to a wav file.

**Comment by upskyy** [comment]
@oh-young-data 
Please check the issue. https://github.com/openspeech-team/openspeech/issues/151#issuecomment-1094997018
