### ISSUE TITLE
test 방법

### ISSUE THREAD

**Issue by miziworld** [openspeech-team/openspeech#52]
안녕하세요,
현재 deepspeech2모델로 1에폭까지 돌린후에 성능검증을 위해 잠깐끊고 test해보려고 합니다.

혹시 last checkpoint에서 저장된 모델로 test만 진행해보고 싶은데
evaluation example 에서 올려주신것처럼
$ python ./openspeech_cli/hydra_eval.py \
    audio=melspectrogram \
    eval.model_name=deepspeech2 \
    eval.dataset_path=$DATASET_PATH \
    eval.checkpoint_path=$CHECKPOINT_PATH \
    eval.manifest_file_path=$MANIFEST_FILE_PATH  
로 경로들을 넣고 실행시켰을때 
![image](https://user-images.githubusercontent.com/17849068/126133527-39a89e8a-3e3c-45ea-a17b-bad3fb6f7769.png)

이러한 에러가 떠서 문의드립니다.
/openspeech/configs/eval.yaml에는 
defaults : 
-audio : null
-eval : default 
로 되어있어서 그런걸까요...?
그리고 만약 트레이닝 중간에 끊게되면 kospeech때처럼 model.pt는 저장이안되고 ckpt만 저장이 되는걸까요?

질문하나만 더드리면 checkpoint에서부터 이어서 트레이닝을 시키고싶은데 그부분은 어디를 참고하면 될까요?

**Comment by sooftware** [comment]
코드를 최신 코드를 반영하셨나요?  
어제 `vocab` 변수를 => `tokenizer`로 바꿨는데, 최신코드라면 거기서 에러가 생기지 않았을까 싶네요.

**Comment by miziworld** [comment]
최신git 으로 업데이트하지않았고 v0.2 사용하고 있습니다

**Comment by sooftware** [comment]
@hasangchun 한번 살펴봐줘요.

**Comment by hasangchun** [comment]
안녕하세요 @miziworld 
>그리고 만약 트레이닝 중간에 끊게되면 kospeech때처럼 model.pt는 저장이안되고 ckpt만 저장이 되는걸까요?
질문하나만 더드리면 checkpoint에서부터 이어서 트레이닝을 시키고싶은데 그부분은 어디를 참고하면 될까요?

네, 최신 코드는 디폴트로 10000 스텝마다 ckpt가 저장되도록 되어있습니다. 또한 현재는 ckpt로 이어서 트레이닝 하는 부분은 구현되어 있지 않습니다. 그리고 버전이 업그레이드 되면서 추가된 것이 많이 있어 최신 코드로 업데이트 하는 것을 추천드립니다!
