### ISSUE TITLE
Need help in training with hyper-parameters

### ISSUE THREAD

**Issue by debasish-mihup** [openspeech-team/openspeech#65]
I am interested in training this model which implements the below paper:
Conformer: Convolution-augmented Transformer for Speech Recognition

I believe the example 1 with **conformer-lstm** would train this model. Is my assumption right?

Also, according to paper there are 3 different models that vary according to the hyper-parameter and I am interested in the "s" version of the model having around 10M parameters. How can I select this version or provide the hyper-parameters?

![Screenshot from 2021-07-28 14-37-40](https://user-images.githubusercontent.com/79203117/127296717-9d714fdb-935a-49d3-ab22-457991f619f1.png)

Also, do you have any script for end-to-end inference (including language model)?

**Comment by sooftware** [comment]
Hello.  
Conformer paper's model is **conformer-transducer** actually.   
You can train this model like below:  
  
```python
$ python ./openspeech_cli/hydra_train.py \
    dataset=librispeech \
    dataset.dataset_download=True \
    dataset.dataset_path=$DATASET_PATH \
    dataset.manifest_file_path=$MANIFEST_FILE_PATH \  
    tokenizer=libri_subword \
    model=conformer_transducer \
    model. encoder_dim=144 \
    model. num_attention_heads=4 \ 
    num_encoder_layers=16 \ 
    num_decoder_layers=1 \ 
    audio=fbank \
    lr_scheduler=warmup_reduce_lr_on_plateau \
    trainer=gpu \
    criterion=transducer
```
  
You can see `conformer-transducer` configuration at [[link]](https://github.com/openspeech-team/openspeech/blob/9c5189fe92f1cf050eb4477c8eb1dd1c98f24534/openspeech/models/conformer/configurations.py#L185)

**Comment by CLC2019** [comment]
Hello!I am also doing the same work as you.Could you have the interest to  communicate with me？

**Comment by debasish-mihup** [comment]
> Hello!I am also doing the same work as you.Could you have the interest to communicate with me？

You are asking me?

**Comment by CLC2019** [comment]
Yes！I am also doing the work to implement the paper with the author's model.

**Comment by CLC2019** [comment]
> > Hello!I am also doing the same work as you.Could you have the interest to communicate with me？
> 
> You are asking me?

Hello!Did you meet the error as follows when you run the project?
![2a26bef7f69381afa29a74e3de0f54d](https://user-images.githubusercontent.com/48012119/128332601-b125ac18-2ba6-49ea-a039-725ab43195c5.png)

**Comment by sooftware** [comment]
@CLC2019 Thank you for letting me know. We will check this problem.  
CC. @hasangchun

**Comment by sooftware** [comment]
@CLC2019 Can you show me the script?

**Comment by CLC2019** [comment]
> @CLC2019 Can you show me the script?

Thank you for your reply.I use the command line to run the project.The commands are showed as follows.
![2](https://user-images.githubusercontent.com/48012119/128353605-f370b01f-235e-4002-9452-3626b1141bda.jpg)

**Comment by CLC2019** [comment]
@sooftware And I use the pycharm to debug,finding the error which exists in warp-rnnt package as follows.
![image](https://user-images.githubusercontent.com/48012119/128356558-12ad737e-00c9-4010-84bd-9ad42b2e34d5.png)

**Comment by sooftware** [comment]
@hasangchun Can you check this problem?

**Comment by hasangchun** [comment]
@CLC2019 When I tested the same command with the latest Git, I was able to confirm that it worked without any errors. And your code doesn't seem to be up-to-date. Could you try again by cloning it to the latest Git?

**Comment by CLC2019** [comment]
@hasangchun Thank you for your reply and suggestion.But there is also a error as follows when I run your the latest project in my device.
![image](https://user-images.githubusercontent.com/48012119/128475791-19b8ce13-7b4d-48c5-ae0d-2e3ad640c224.png)

**Comment by hasangchun** [comment]
@CLC2019   Can I know the your gpu status in the script?

**Comment by CLC2019** [comment]
@hasangchun My GPU is GeForce RTX 2080 Ti which is 10GB memory.
![image](https://user-images.githubusercontent.com/48012119/128502062-89fdfdaa-e686-4a5a-a425-a863b1f6ce10.png)

**Comment by hasangchun** [comment]
@CLC2019 I'm really sorry for replying late. We tested with a single gpu. Are you still getting the error?

**Comment by CLC2019** [comment]
@hasangchun Thank you for your reply.I think the error sources from the package--warp_rnnt. The error occurs on my server,but  on other server the warp_rnnt runs without errors. Maybe my environment doesn't match the warp_rnnt.Could you tell me your dependences of the warp_rnnt?Thanks a lot.

**Comment by CLC2019** [comment]
@hasangchun I also test with warp-rnnt==0.4.0.My CUDA version is 10.0,pytorch==1.6,and cudatoolkit==10.1.Could you give me your information?Thanks a lot.

**Comment by hasangchun** [comment]
@CLC2019 My CUDA version is 11.4, pytorch==1.9.0 and cudatoolkit==10.2.  Thanks a lot.

**Comment by wuxiuzhi738** [comment]
can only use transducer,  I used ctc and   joint ctc cross entorpy.
