### ISSUE TITLE
이메일 주소로 메일을 보내지 못하였습니다.

### ISSUE THREAD

**Issue by bandoche** [openspeech-team/openspeech#69]
# ❓ Questions & Help
<img width="628" alt="Screenshot 2021-07-30 오전 9 34 13" src="https://user-images.githubusercontent.com/1097495/127582355-bcf15b7f-424a-4159-a7d2-06d045e68f92.png">

지메일에서 요청 메일을 보냈는데, 주소가 없다고 나옵니다. 

## Details

```
주소를 찾을 수 없음
openspeech-team@gmail.com 주소를 찾을 수 없거나 해당 주소에서 메일을 받을 수 없어 메일이 전송되지 않았습니다.
```

혹시 이메일 주소가 변경되었을지 확인 부탁드립니다.

**Comment by hasangchun** [comment]
안녕하세요. 이메일 주소는 openspeech.team@gmail.com 입니다. 혹시 어떤 요청 메일인지 알 수 있을까요?
