### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sos_id'

### ISSUE THREAD

**Issue by phm1231** [openspeech-team/openspeech#70]
# ❓ Questions & Help
초심자여서 기초적인 질문이 존재할 수 있는 점 양해 부탁드립니다..!
kospeech에서 제공해주던 모델 그대로 conformer-large 를 이용하여 학습을 진행하다가 loss nan으로 인해 학습을 멈추고 openspeech를 사용하여 음성인식기를 제작해보려고 했습니다.

먼저, 실행 명령은 readme에 나와있는 ksponspeech 데이터 학습과 동일하게 실행하였습니다.
![train_execute](https://user-images.githubusercontent.com/74368938/127978933-17e798ce-583c-4814-b35d-4fb7e612405e.png)

DATASET_PATH 에는 aihub에서 받은 KsponSpeech_01 ... 05 폴더가 위치해있으며
MANIFEST_FILE_PATH 에는 이메일을 통해 받은 kspon_character_manifest.txt 파일 경로가 저장되어있습니다.
TEST_DATASET_PATH 에는 aihub에서 받은 eval_clean과 eval_other 폴더가 위치해있으며
TEST_MANIFEST_DIR 에는 역시 이메일을 통해 받은 kspon_character_manifest.txt가 위치한 폴더 명을 저장해두었습니다.

먼저, 이 지점에서 질문을 드리고 싶은 것이 각 패스가 의미하는 파일들이 올바르게 저장되어 있는지 여쭤보고 싶습니다.

깃 클론 이후 했던 과정을 전부 나열해드리면
![syntaxerror](https://user-images.githubusercontent.com/74368938/127977600-600944d8-0d76-4e72-a7d9-794f17cf57b8.png)
로 인하여
openspeech/callbacks.py 에서

![callbacks](https://user-images.githubusercontent.com/74368938/127978022-d19a07a4-56bf-48e8-9cba-44ceb5444858.png)

로 수정하였고,
이후 재실행하여 
OSError: Character label file (csv format) doesn't exist ../../../aihub_labels.csv
가 발생하였습니다.
![log1](https://user-images.githubusercontent.com/74368938/127978438-b6eccdc4-2e78-41fa-b8a5-f3903b3da579.png)
![log2](https://user-images.githubusercontent.com/74368938/127978449-2c03dbbc-2dfe-4ec9-a4cd-394ff81a6379.png)
![log3](https://user-images.githubusercontent.com/74368938/127978457-03444f8d-6d86-4c43-8c63-9394ea96ff19.png)
![log4](https://user-images.githubusercontent.com/74368938/127978462-65917c0a-9723-42db-a25f-c7183a84356d.png)

때문에 ./opensppech/tokenizers/ksponspeech/character.py 에서
![character](https://user-images.githubusercontent.com/74368938/127978707-100dbca2-46f7-4646-aea3-5e55c2db88d0.png)

로 절대경로로 설정해주었습니다.
kspon_character_labels.csv 파일은 aihub 승인 스크린샷을 보내드린 후 받은 파일과 동일합니다.
이후 재실행하였더니
![last_log](https://user-images.githubusercontent.com/74368938/127978856-f892a72f-3873-4391-af1d-3aa14c391007.png)

위와 같은 결과가 나왔습니다.
여기서 다시 질문을 드리고 싶은 점이, 위에 했던 과정에서 오류를 일으킬 만한 점이 있었는지와
기본 설정된 aihub_labels.csv 파일이 제가 설정해 준 kspon_character_labels.csv 파일이 맞는지,
        아니라면 aihub_labels.csv 파일은 무엇이며 어떻게 얻을 수 있는지,

마지막으로 위 과정에서 특별한 문제가 없다면, sos_id attribute에 대한 error는 어떻게 처리해야 하는 지에 관해서 입니다.

다소 글이 길어진 점 죄송합니다. 사소한 것 하나가 크게 영향을 미칠까봐 건드렸던 모든 것을 정리해서 적어보았습니다.
답변 기다리겠습니다!

**Comment by sooftware** [comment]
@hasangchun 확인해줘요.

**Comment by hasangchun** [comment]
>DATASET_PATH 에는 aihub에서 받은 KsponSpeech_01 ... 05 폴더가 위치해있으며
MANIFEST_FILE_PATH 에는 이메일을 통해 받은 kspon_character_manifest.txt 파일 경로가 저장되어있습니다.
TEST_DATASET_PATH 에는 aihub에서 받은 eval_clean과 eval_other 폴더가 위치해있으며
TEST_MANIFEST_DIR 에는 역시 이메일을 통해 받은 kspon_character_manifest.txt가 위치한 폴더 명을 저장해두었습니다.
먼저, 이 지점에서 질문을 드리고 싶은 것이 각 패스가 의미하는 파일들이 올바르게 저장되어 있는지 여쭤보고 싶습니다.

TEST_MANIFEST_DIR에는 eval_clean.trn과 eval_other.trn 파일이 있는 폴더 명으로 해주시면 될 것 같습니다. 
관련된 [link](https://github.com/openspeech-team/openspeech/blob/main/openspeech/datasets/ksponspeech/preprocess/preprocess.py#L160) 첨부드립니다.
  


>기본 설정된 aihub_labels.csv 파일이 제가 설정해 준 kspon_character_labels.csv 파일이 맞는지,
아니라면 aihub_labels.csv 파일은 무엇이며 어떻게 얻을 수 있는지,

기본 설정된 aihub_labels.csv는 default로 설정된 것이라 설정해주신  kspon_character_labels.csv 로 진행해주시면 될 것 같습니다.

수정하셔서 다시한번 실행 부탁드립니다.

**Comment by hasangchun** [comment]
그리고 joint_ctc_cross_entropy criterion을 사용하시려면 listen_attend_spell이 아닌 joint_ctc_listen_attend_spell 모델을 사용하셔야 합니다. [link](https://github.com/openspeech-team/openspeech/wiki/Criterion-suitable-for-the-model) 참고 부탁드립니다!

**Comment by phm1231** [comment]
빠른 답변 감사합니다. 위에서 말씀해주신 모든 사항을 올바르게 반영했음에도 불구하고 NoneType object has no attribute 'sos_id' 에러가 발생합니다.

개인적으로 함수를 따라가보았더니
openspeech/datasets/ksponspeech/lit_data_module.py 에 속해있는 함수
prepare_data() 부분에서
return TOKENIZER_REGISTRY[self.configs.tokenizer.unit](self.configs)
이전에 print(TOKENIZER_REGISTRY[self.configs.tokenizer.unit](self.configs)) 로 확인해보았더니
올바른 값이 뜨는 것을 확인했습니다.

다만, openspeech_cli/hydra_train.py 에 속해있는 함수
hydra_main() 부분에서
tokenizer = data_module.prepare_data() 를 통해서 받은 tokenizer 값을
print(tokenizer)를 통해 확인해보았더니 None이 출력되었습니다.

좌측 상단 터미널이 lit_data_module.py 파일
우측 상단 터미널이 hydra_train.py 파일
하단 터미널이 실행 결과값 중 로그입니다. 잘린 부분의 마지막에는 NoneType Error로 동일합니다.

![why not](https://user-images.githubusercontent.com/74368938/128064754-5d29d71b-0ad0-410c-86e1-f7422063c04f.png)

죄송하지만 부탁드립니다.

**Comment by hasangchun** [comment]
저도 동일한 커맨드로 동일하게 tokenizer 출력해보았는데 올바르게 출력이 되어서 번거로우시겠지만 최신 깃으로 클론하여 다시한번 실행해주시면 감사하겠습니다.

**Comment by eastjin218** [comment]
저도 방금 최신 깃을 이용해서 해보았으나 동일한 문제가 발생합니다. 
openspeech/datasets/ksponspeech/lit_data_module.py 에 속해있는 함수
prepare_data() 부분에서
아래부분을 추가하여 
print('--TOKENIZER_REGISTRY[self.configs.tokenizer.unit](self.configs).sos_id--')
print(TOKENIZER_REGISTRY[self.configs.tokenizer.unit](self.configs).sos_id)
아래 결과를 확인하였습니다.
--TOKENIZER_REGISTRY[self.configs.tokenizer.unit](self.configs).sos_id--
1
그런데 
hydra_main() 부분에서 tokenizer가 동일하게 
None 입니다 
해결방법을 알려주시면 감사하겠습니다.

**Comment by phm1231** [comment]
저도 다시 깃을 받아 실행해봤으나 동일한 오류입니다.

**Comment by hasangchun** [comment]
https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html#prepare-data

prepare_data 메소드를 오버라이딩 하는 과정에서 메소드의 이름과 매개변수, 반환형이 같아야하는데 그렇지 못해서 발생한 에러라고 생각합니다. 위의 첨부된 링크를 참고했을 때, 기존 prepare_data 메소드의 return값이 None이여서 None값이 들어간 것 같습니다.

**Comment by w4-donguk** [comment]
안녕하세요, 동일한 에러를 직면하였고 우선 저도 `hydra_main.py` 에서 아래 line을 추가하여 따로 tokenizer 를 import 하는 방식으로 해결하긴 했는데요, 현재로써는 이렇게 해결하는게 최선일까요?

`tokenizer = TOKENIZER_REGISTRY['kspon_character'](configs)`
