### ISSUE TITLE
Validation sanity check: Error executing job with overrides

### ISSUE THREAD

**Issue by Youngmi-Park** [openspeech-team/openspeech#87]
# ❓ Questions & Help

전에 질문드렸던 **FileNotFoundError**는 dataset.dataset_path, dataset.manifest_file_path, dataset.test_dataset_path, dataset.test_manifest_dir, tokenizer.vocab_path 전부 절대경로로 지정해주었더니 해결되었습니다.

추가로 발생하는 에러에 대해서 문의드리고 싶어 issue남깁니다.

-  TypeError: load_audio() missing 1 required positional argument: 'sample_rate' 는 최근에 업데이트하신 코드에서 돌리니 해결
- 위의 에러를 해결하고 나서 실행시키니 Validation sanity check 실행 중에 오류가 발생합니다.

## Details

![스크린샷, 2021-09-02 16-12-30](https://user-images.githubusercontent.com/53163222/131801051-022ada1c-696c-4afa-a3d3-0134e4139c8d.png)
![스크린샷, 2021-09-02 16-12-40](https://user-images.githubusercontent.com/53163222/131801054-faf86b66-4f1c-4c69-92f6-3c7a87f6817a.png)
![스크린샷, 2021-09-02 16-12-52](https://user-images.githubusercontent.com/53163222/131801057-da30a764-ccc7-44df-b664-fbcdff838e66.png)
![스크린샷, 2021-09-02 16-12-57](https://user-images.githubusercontent.com/53163222/131801058-a14619a5-f4c6-414c-be6b-a84a36d9e396.png)
![스크린샷, 2021-09-02 16-13-05](https://user-images.githubusercontent.com/53163222/131801060-0c09a9b7-2218-44ee-8a96-fea5d950b536.png)
![스크린샷, 2021-09-02 16-13-13](https://user-images.githubusercontent.com/53163222/131801062-f61c1049-7083-4217-bce6-73f305788ba5.png)
![스크린샷, 2021-09-02 16-13-29](https://user-images.githubusercontent.com/53163222/131801066-e826d463-2773-4d72-bdfe-392647822bf8.png)

**Comment by sooftware** [comment]
확인해보겠습니다.

**Comment by sooftware** [comment]
타입이 튜플이여서 생긴 에러였습니다.  
list로 형변환해주는 코드를 업데이트 했습니다. 최신 코드로 실행해보시겠어요?

**Comment by Youngmi-Park** [comment]
감사합니다, 에러 해결되었습니다!
