### ISSUE TITLE
script  bug 

### ISSUE THREAD

**Issue by wuxiuzhi738** [openspeech-team/openspeech#92]
## Information

Model I am using (ListenAttendSpell, Transformer, Conformer ...):

The problem arises when using:

in openspeech/datasets/aishell/preprocess.py, line 137,audio_paths should be keys.

**Comment by hasangchun** [comment]
Could you show the log in detail?

**Comment by wuxiuzhi738** [comment]
sorry,I don't keep the log  and the  program  runs without error when use audio_paths in openspeech/datasets/aishell/preprocess.py,  line 137.       However, it is certain that if  we use audio_paths variable , it will cause a mismatch between the text label and the path  in aishell_manifest.txt. I have forked the project and corrected this problem in my repository.

**Comment by hasangchun** [comment]
Oh really? If it's possible for you to send us a pull request, we'd appreciate it.

**Comment by wuxiuzhi738** [comment]
I have sent it.

**Comment by sooftware** [comment]
resolved by #95
