### ISSUE TITLE
why the default config value **conv_kernel_size** of conformer is 31? The conformer paper use 32 as the default value

### ISSUE THREAD

**Issue by wl-junlin** [openspeech-team/openspeech#93]
# ❓ Questions & Help

why the default config value **conv_kernel_size** of conformer is 31? The conformer paper use 32 as the default value

**Comment by sooftware** [comment]
It is because of the convenience of implementation.

**Comment by wl-junlin** [comment]
> It is because of the convenience of implementation.

emmm, sorry, can you be more specific? I don't see how it brings any convenience.

**Comment by wuxiuzhi738** [comment]
> > It is because of the convenience of implementation.
> 
> emmm, sorry, can you be more specific? I don't see how it brings any convenience.

hey,bro, are you a chinese, you have completed the trainning with conformer model?  What about your predicted results?

**Comment by sooftware** [comment]
Ah, sorry. I accidentally said it wrong. As you said, the conformer's default convolutional kernel size is 32 in paper.  
But, as far as I know, the kernel size is good in odd numbers. So I looked at other implementations, and they were the same as I thought. 31 was often used. Of course, it's just a default setting, and you can change it and use it.

**Comment by wl-junlin** [comment]
> Ah, sorry. I accidentally said it wrong. As you said, the conformer's default convolutional kernel size is 32 in paper.
> But, as far as I know, the kernel size is good in odd numbers. So I looked at other implementations, and they were the same as I thought. 31 was often used. Of course, it's just a default setting, and you can change it and use it.

I get it. thanks

> > > It is because of the convenience of implementation.
> > 
> > 
> > emmm, sorry, can you be more specific? I don't see how it brings any convenience.
> 
> hey,bro, are you a chinese, you have completed the trainning with conformer model? What about your predicted results?

yes，I am on the way

**Comment by wuxiuzhi738** [comment]
> > It is because of the convenience of implementation.
> 
> emmm, sorry, can you be more specific? I don't see how it brings any convenience.

方便交流一下心得吗？

**Comment by wl-junlin** [comment]
> 方便交流一下心得吗？

ok

**Comment by wuxiuzhi738** [comment]
> > 方便交流一下心得吗？
> 
> ok

邮箱：liuhaoxuan_edu@163.com
或者你方便的话，加一下微信也行
