### ISSUE TITLE
Requesting `Manifest`, `Vocab` and `SP-Model` for KsponSpeech

### ISSUE THREAD

**Issue by jun-danieloh** [openspeech-team/openspeech#96]
# ❓ Questions & Help
I am requesting `Manifest`, `Vocab` and `SP-Model` files for experiments with KsponSpeech dataset. I did request files on the link in README but I didn't get responses yet. Could any guys can help me? If it is okay, can you send them to my email, `jun.danieloh@gmail.com`?

**Comment by sooftware** [comment]
Hi! Sorry. I must have missed the mail. Can you send it again? If you send me the approval details of KsponSpeech, I will approve it right away.

**Comment by jun-danieloh** [comment]
@sooftware 

Thank you for your quick response. I just sent a permission email by `jun.danieloh@gmail.com`. Do I need to request it separately for each Manifest, Vocab, and SP-Model files? I just sent one email to `opeenspeech.team@gmail.com`. If needed further actions, please let me know.

**Comment by jun-danieloh** [comment]
@sooftware 

I just got two files. Any other Vocab or SP-Model files are not needed for training?

**Comment by sooftware** [comment]
@jun-danieloh  I just approved another one. Did they all get approved?

**Comment by jun-danieloh** [comment]
@sooftware Just these two files, `kspon_character_manifest.txt` and `kspon_subword_manifest.txt` are approved. Are they enough to run training?

**Comment by jun-danieloh** [comment]
@sooftware Also, what is the path for `dataset.test_manifest_dir`??

This is my current training script. Can you please tell me whether I am doing right?
```
python ./openspeech_cli/hydra_train.py \
        dataset=ksponspeech \
        dataset.dataset_path= /mnt/dataset/KsponSpeech/kspon/kspon \
        dataset.manifest_file_path= /mnt/dataset/KsponSpeech/kspon/kspon_character_manifest.txt \
        dataset.test_dataset_path= /mnt/dataset/KsponSpeech/kspon/kspon_eval \
        dataset.test_manifest_dir= \
        tokenizer=kspon_character \
        model=joint_ctc_listen_attend_spell \
        audio=melspectrogram \
        lr_scheduler=warmup_reduce_lr_on_plateau \
        trainer=gpu \
        criterion=joint_ctc_cross_entropy
```

My kspon directory:
```
jun1.oh@elf-desktop:/mnt/dataset/KsponSpeech/kspon/kspon$ ls                         
KsponSpeech_01  KsponSpeech_02  KsponSpeech_03  KsponSpeech_04  KsponSpeech_05     
```

My kspon_eval directory:
```
jun1.oh@elf-desktop:/mnt/dataset/KsponSpeech/kspon/kspon_eval$ ls  
eval_clean  eval_other  KsponSpeech_eval.zip   
```

**Comment by sooftware** [comment]
Specify test_manifest_dir, and if test_manifest_path is not valid, will automatically preprocess and create it.
