### ISSUE TITLE
UnicodeDecodeError when reading ksponspeech manifest file

### ISSUE THREAD

**Issue by jun-danieloh** [openspeech-team/openspeech#98]
## Environment info
- Platform: Ubuntu 18.04
- Python version: 3.8.3
- PyTorch version (GPU?): 1.7.0 
- Using GPU in script?: Yes

  
## Information

Model I am using (ListenAttendSpell, Transformer, Conformer ...):

The problem arises when using:
* [v] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

## To reproduce

1. Follow the script below. I set required files accordingly based on README.
```
root@elf-desktop:/home/jun1.oh/workspace/openspeech# cat train_kspon.sh
#!/bin/bash
python ./openspeech_cli/hydra_train.py \
        dataset=ksponspeech \
    dataset.dataset_path=/mnt/dataset/KsponSpeech/kspon/kspon/ \
    dataset.manifest_file_path=/mnt/dataset/KsponSpeech/kspon/kspon_character_manifest.txt \
    dataset.test_dataset_path=/mnt/dataset/KsponSpeech/kspon/kspon_eval/ \
    dataset.test_manifest_dir=/mnt/dataset/KsponSpeech/kspon/scripts/ \
    tokenizer=kspon_character \
    model=joint_ctc_listen_attend_spell \
    audio=melspectrogram \
    lr_scheduler=warmup_reduce_lr_on_plateau \
    trainer=gpu \
    criterion=joint_ctc_cross_entropy
```

## Expected behavior
My code works well with LibriSpeech dataset. I am trying to run the code with KsponSpeech dataset now. However, it is giving errors while reading a `kspon_character_manifest.txt` file with errors below.

```
[2021-09-13 10:37:41,028][openspeech.utils][INFO] - PyTorch version : 1.7.0
Error executing job with overrides: ['dataset=ksponspeech', 'dataset.dataset_path=/mnt/dataset/KsponSpeech/kspon/kspon/', 'dataset.manifest_file_path=/mnt/dataset/KsponSpeech/kspon/kspon_character_manifest.txt', 'dataset.test_dataset_pat
h=/mnt/dataset/KsponSpeech/kspon/kspon_eval/', 'dataset.test_manifest_dir=/mnt/dataset/KsponSpeech/kspon/scripts/', 'tokenizer=kspon_character', 'model=joint_ctc_listen_attend_spell', 'audio=melspectrogram', 'lr_scheduler=warmup_reduce_l
r_on_plateau', 'trainer=gpu', 'criterion=joint_ctc_cross_entropy']
Traceback (most recent call last):
  File "./openspeech_cli/hydra_train.py", line 60, in <module>
    hydra_main()
  File "/opt/conda/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "./openspeech_cli/hydra_train.py", line 48, in hydra_main
    data_module.setup(tokenizer=tokenizer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/jun1.oh/workspace/openspeech/openspeech/datasets/ksponspeech/lit_data_module.py", line 156, in setup
    audio_paths, transcripts = self._parse_manifest_file()
  File "/home/jun1.oh/workspace/openspeech/openspeech/datasets/ksponspeech/lit_data_module.py", line 120, in _parse_manifest_file
    for idx, line in enumerate(f.readlines()):
  File "/opt/conda/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 55: invalid start byte
``` 

When I tried to set 'cp949' encoding instead of 'utf-8', it clears this issue but generates another errors so I think it is better to debug this one first.

Thanks,
Daniel

**Comment by sooftware** [comment]
I think the route is wrong.  Designate it as the absolute route.

**Comment by sooftware** [comment]
I'll check about tomorrow.

**Comment by jun-danieloh** [comment]
When I tried to encode manifest file with `cp949`, it went through but the encoding of path is somewhat messed up. I believe the absolute path is okay.

**Comment by sooftware** [comment]
@hasangchun Can you check? @jun-danieloh I'm sorry. I'm personally busy right now, so I couldn't check today.

**Comment by w4-donguk** [comment]
Same as me. decoding by cp949 returns somewhat gibberish sentence, but utf-8 decoding returns normal sentence.

utf-8 had some problem on some chars but I ignored that case by opening like below : 
**open(file_path, 'r', encoding='utf-8', errors='ignore')**

Not very sure but I assume our ksponspeech dataset encoding format is different with what they using?

**Comment by jun-danieloh** [comment]
@w4-donguk Does your code work with `open(file_path, 'r', encoding='utf-8', errors='ignore')`? Mine still had some errors.

**Comment by w4-donguk** [comment]
I'm facing some CUDA issue now, but seems like there're no problem about encoding issue so far. what kind of error did you get?

**Comment by jun-danieloh** [comment]
@w4-donguk 

Where did you put `open(file_path, 'r', encoding='utf-8', errors='ignore')`? 

I put this edit in `lit_data_module.py` as below:
```
...
        audio_paths = list()
        transcripts = list()

        with open(self.configs.dataset.manifest_file_path, encoding=self.encoding, errors='ignore') as f: 
...
```

After this edit, `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 55: invalid start byte` is gone and it looks like this issue is resolved.

However, I got another error as below:
```
  File "/home/jun1.oh/workspace/openspeech/openspeech/datasets/ksponspeech/lit_data_module.py", line 197, in val_dataloader
    valid_sampler = sampler(self.dataset['valid'], batch_size=self.configs.trainer.batch_size)
  File "/home/jun1.oh/workspace/openspeech/openspeech/data/sampler.py", line 73, in __init__
    audio_lengths = [self._get_audio_length(audio_path) for audio_path in data_source.audio_paths]
  File "/home/jun1.oh/workspace/openspeech/openspeech/data/sampler.py", line 73, in <listcomp>
    audio_lengths = [self._get_audio_length(audio_path) for audio_path in data_source.audio_paths]
  File "/home/jun1.oh/workspace/openspeech/openspeech/data/sampler.py", line 95, in _get_audio_length
    return len(load_audio(os.path.join(self.data_source.dataset_path, audio_path), sample_rate=16000))
TypeError: object of type 'NoneType' has no len()
```

So I tried to print out audio path and it is giving it as below. Backslash is somewhat flipped. 
```
Daniel Debugging
KsponSpeech_05\KsponSpeech_0621\KsponSpeech_620119.pcm
/mnt/dataset/KsponSpeech/kspon/kspon/
```

Didn't you see this error?

**Comment by sooftware** [comment]
@jun-danieloh 
Why don't you run it without specifying a `manifest_file_path`?  
I think the file may be encoded incorrectly. If the manifest_file_path is not specified, it will automatically generate it.

**Comment by jun-danieloh** [comment]
@sooftware 

Original manifest file that I downloaded from README has the file path syntax as below.
`KsponSpeech_01\KsponSpeech_0001\KsponSpeech_000012.pcm`

I edited the file path syntax as below and it works well now.
`KsponSpeech_01/KsponSpeech_0001/KsponSpeech_000008.pcm`

I got CUDA issues as @w4-donguk mentioned above and maybe it is the same issue. Let me continue debugging on this.
